import "../styles/app.scss";

import { NavItemProps } from "@/views/Navigation/Navigation";
import { Navigation } from "@/views/Navigation/Navigation";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const navItemProps: NavItemProps[] = [
  {
    label: "Über uns",
    href: "./",
    childs: [
      {
        label: "Wir stellen uns vor",
        href: "/ueber-uns/wir-stellen-uns-vor",
      },
      {
        label: "So finden Sie uns",
        href: "/ueber-uns/so-finden-sie-uns",
      },
      {
        label: "Unsere Fahrzeuge",
        href: "/ueber-uns/",
      },
      {
        label: "Unsere Strecke",
        href: "/ueber-uns/unsere-strecke",
      },
      {
        label: "Die ehemalige Bergedorf-Geesthachter Eisenbahn",
        href: "",
      },
      {
        label: "Das Buch zur Strecke",
        href: "/ueber-uns/das-buch-zur-strecke",
      },
      {
        label: "Wir suchen (neue Mitglieder, großzügige Spender usw.)",
        href: "/ueber-uns/wir-suchen",
      },
      {
        label: "Impressum",
        href: "/ueber-uns/",
      },
    ],
  },
  {
    label: "Fahrpläne & Reservierungen",
    href: "",
    childs: [
      {
        label: "Fahrplan 2023",
        href: "",
      },
      {
        label: "Fahrpreise ab 2023",
        href: "",
      },
      {
        label: "Anfragen und Reservierunge",
        href: "",
      },
    ],
  },
  {
    label: "Links & Sonstiges",
    href: "",
    childs: [
      {
        label: "Eisenbahnbücher aus Nachlass",
        href: "",
      },
      {
        label: "kohlebefeuerten Raddampfer",
        href: "",
      },
      {
        label: "kohlebefeuerten Eisbrecher",
        href: "",
      },
      {
        label: "Links zu anderen Bahnen",
        href: "",
      },
    ],
  },
];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>Eisenbahn tuut tuut </title>
      </head>
      <body>
        <Navigation data={navItemProps}></Navigation>
        {children}
      </body>
    </html>
  );
}
